SELECT MAX(SALARY) FROM hr.employees;
SELECT MAX(SALARY)- MIN(SALARY) FROM hr.employees;
SELECT JOB_ID, AVG(SALARY) AS `Media salarial` FROM hr.employees
GROUP BY JOB_ID
ORDER BY `Media salarial` DESC;

SELECT SUM(SALARY) FROM hr.employees;

SELECT ROUND(MAX(SALARY), 2) AS maior, MIN(SALARY) AS menor,
SUM(SALARY) AS soma, ROUND(AVG(SALARY), 2) AS media FROM hr.employees;

SELECT COUNT(JOB_ID) FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) AS total FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) AS total FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID NOT IN ('IT_PROG');

SELECT department_id, COUNT(EMPLOYEE_ID) AS funcionarios,
AVG(SALARY) AS total FROM hr.employees
GROUP BY department_id
HAVING funcionarios > 10;

SELECT PHONE_NUMBER,
	CASE	
		WHEN SUBSTRING(PHONE_NUMBER, 1, 3) = 515 THEN REPLACE(PHONE_NUMBER, 515, 777)
	END AS `novo numero`
FROM hr.employees;

SELECT *, LENGTH(FIRST_NAME) AS QTD FROM hr.employees
WHERE LENGTH(FIRST_NAME) >= 8
ORDER BY QTD;

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) from hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) from hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) from hr.employees;

SELECT UCASE(FIRST_NAME) AS nome FROM hr.employees;

SELECT LAST_NAME, HIRE_DATE FROM hr.employees
WHERE DATE(HIRE_DATE) > '1987-06-01'
ORDER BY HIRE_DATE ASC;

SELECT FIRST_NAME, LAST_NAME, DATEDIFF(NOW(), HIRE_DATE) FROM hr.employees;